package libreria.modelo;
// Generated 11 nov 2024, 17:29:00 by Hibernate Tools 5.4.33.Final

/**
 * DisponibilidadId generated by hbm2java
 */
public class DisponibilidadId implements java.io.Serializable {

	private int codigoLibro;
	private int codigoTienda;

	public DisponibilidadId() {
	}

	public DisponibilidadId(int codigoLibro, int codigoTienda) {
		this.codigoLibro = codigoLibro;
		this.codigoTienda = codigoTienda;
	}

	public int getCodigoLibro() {
		return this.codigoLibro;
	}

	public void setCodigoLibro(int codigoLibro) {
		this.codigoLibro = codigoLibro;
	}

	public int getCodigoTienda() {
		return this.codigoTienda;
	}

	public void setCodigoTienda(int codigoTienda) {
		this.codigoTienda = codigoTienda;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DisponibilidadId))
			return false;
		DisponibilidadId castOther = (DisponibilidadId) other;

		return (this.getCodigoLibro() == castOther.getCodigoLibro())
				&& (this.getCodigoTienda() == castOther.getCodigoTienda());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodigoLibro();
		result = 37 * result + this.getCodigoTienda();
		return result;
	}

}
