package filmoteca.modelo;
// Generated 26 nov 2024, 19:12:09 by Hibernate Tools 5.4.33.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import org.hibernate.Hibernate;

/**
 * Pelicula generated by hbm2java
 */
public class Pelicula implements java.io.Serializable {

	private Integer codigo;
	private Saga saga;
	private String titulo;
	private int agnoEstreno;
	private int duracion;
	private BigDecimal recaudacion;
	private BigDecimal puntuacion;
	private Set personajes = new HashSet(0);

	public Pelicula() {
	}

	public Pelicula(String titulo, int agnoEstreno, int duracion, BigDecimal recaudacion, BigDecimal puntuacion) {
		this.titulo = titulo;
		this.agnoEstreno = agnoEstreno;
		this.duracion = duracion;
		this.recaudacion = recaudacion;
		this.puntuacion = puntuacion;
	}

	public Pelicula(Saga saga, String titulo, int agnoEstreno, int duracion, BigDecimal recaudacion,
			BigDecimal puntuacion, Set personajes) {
		this.saga = saga;
		this.titulo = titulo;
		this.agnoEstreno = agnoEstreno;
		this.duracion = duracion;
		this.recaudacion = recaudacion;
		this.puntuacion = puntuacion;
		this.personajes = personajes;
	}

	public Integer getCodigo() {
		return this.codigo;
	}

	public void setCodigo(Integer codigo) {
		this.codigo = codigo;
	}

	public Saga getSaga() {
		return this.saga;
	}

	public void setSaga(Saga saga) {
		this.saga = saga;
	}

	public String getTitulo() {
		return this.titulo;
	}

	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}

	public int getAgnoEstreno() {
		return this.agnoEstreno;
	}

	public void setAgnoEstreno(int agnoEstreno) {
		this.agnoEstreno = agnoEstreno;
	}

	public int getDuracion() {
		return this.duracion;
	}

	public void setDuracion(int duracion) {
		this.duracion = duracion;
	}

	public BigDecimal getRecaudacion() {
		return this.recaudacion;
	}

	public void setRecaudacion(BigDecimal recaudacion) {
		this.recaudacion = recaudacion;
	}

	public BigDecimal getPuntuacion() {
		return this.puntuacion;
	}

	public void setPuntuacion(BigDecimal puntuacion) {
		this.puntuacion = puntuacion;
	}

	public Set getPersonajes() {
		return this.personajes;
	}

	public void setPersonajes(Set personajes) {
		this.personajes = personajes;
	}

	@Override
	public String toString() {
		;
		return "Pelicula [codigo=" + codigo + ", codigo saga=" + saga.getCodigo() + ", titulo=" + titulo + ", agnoEstreno=" + agnoEstreno
				+ ", duracion=" + duracion + ", recaudacion=" + recaudacion + ", puntuacion=" + puntuacion + "]";
	} //", saga=" + saga.getNombre() +

}
