package filmoteca.modelo;
// Generated 26 nov 2024, 19:12:09 by Hibernate Tools 5.4.33.Final

/**
 * Personaje generated by hbm2java
 */
public class Personaje implements java.io.Serializable {

	private PersonajeId id;
	private Actor actor;
	private Pelicula pelicula;
	private String nombre;

	public Personaje() {
	}

	public Personaje(PersonajeId id, Actor actor, Pelicula pelicula, String nombre) {
		this.id = id;
		this.actor = actor;
		this.pelicula = pelicula;
		this.nombre = nombre;
	}

	public PersonajeId getId() {
		return this.id;
	}

	public void setId(PersonajeId id) {
		this.id = id;
	}

	public Actor getActor() {
		return this.actor;
	}

	public void setActor(Actor actor) {
		this.actor = actor;
	}

	public Pelicula getPelicula() {
		return this.pelicula;
	}

	public void setPelicula(Pelicula pelicula) {
		this.pelicula = pelicula;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

}
