package filmoteca.modelo;
// Generated 26 nov 2024, 19:12:09 by Hibernate Tools 5.4.33.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Saga generated by hbm2java
 */
public class Saga implements java.io.Serializable {

	private Integer codigo;
	private String nombre;
	private String descripcion;
	private int cantidad;
	private BigDecimal puntuacionMedia;
	private Set peliculas = new HashSet(0);

	public Saga() {
	}

	public Saga(String nombre, int cantidad) {
		this.nombre = nombre;
		this.cantidad = cantidad;
	}

	public Saga(String nombre, String descripcion, int cantidad, BigDecimal puntuacionMedia, Set peliculas) {
		this.nombre = nombre;
		this.descripcion = descripcion;
		this.cantidad = cantidad;
		this.puntuacionMedia = puntuacionMedia;
		this.peliculas = peliculas;
	}

	public Integer getCodigo() {
		return this.codigo;
	}

	public void setCodigo(Integer codigo) {
		this.codigo = codigo;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public int getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(int cantidad) {
		this.cantidad = cantidad;
	}

	public BigDecimal getPuntuacionMedia() {
		return this.puntuacionMedia;
	}

	public void setPuntuacionMedia(BigDecimal puntuacionMedia) {
		this.puntuacionMedia = puntuacionMedia;
	}

	public Set getPeliculas() {
		return this.peliculas;
	}

	public void setPeliculas(Set peliculas) {
		this.peliculas = peliculas;
	}

}
