package centroformacion.modelo;
// Generated 3 dic 2024, 19:02:01 by Hibernate Tools 5.4.33.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Ciclo generated by hbm2java
 */
public class Ciclo implements java.io.Serializable {

	private int codigo;
	private String denominacion;
	private String familia;
	private String nivel;
	private int duracion;
	private int agnoTitulo;
	private Set modulos = new HashSet(0);

	public Ciclo() {
	}

	public Ciclo(int codigo, String denominacion, String familia, String nivel, int duracion, int agnoTitulo) {
		this.codigo = codigo;
		this.denominacion = denominacion;
		this.familia = familia;
		this.nivel = nivel;
		this.duracion = duracion;
		this.agnoTitulo = agnoTitulo;
	}

	public Ciclo(int codigo, String denominacion, String familia, String nivel, int duracion, int agnoTitulo,
			Set modulos) {
		this.codigo = codigo;
		this.denominacion = denominacion;
		this.familia = familia;
		this.nivel = nivel;
		this.duracion = duracion;
		this.agnoTitulo = agnoTitulo;
		this.modulos = modulos;
	}

	public int getCodigo() {
		return this.codigo;
	}

	public void setCodigo(int codigo) {
		this.codigo = codigo;
	}

	public String getDenominacion() {
		return this.denominacion;
	}

	public void setDenominacion(String denominacion) {
		this.denominacion = denominacion;
	}

	public String getFamilia() {
		return this.familia;
	}

	public void setFamilia(String familia) {
		this.familia = familia;
	}

	public String getNivel() {
		return this.nivel;
	}

	public void setNivel(String nivel) {
		this.nivel = nivel;
	}

	public int getDuracion() {
		return this.duracion;
	}

	public void setDuracion(int duracion) {
		this.duracion = duracion;
	}

	public int getAgnoTitulo() {
		return this.agnoTitulo;
	}

	public void setAgnoTitulo(int agnoTitulo) {
		this.agnoTitulo = agnoTitulo;
	}

	public Set getModulos() {
		return this.modulos;
	}

	public void setModulos(Set modulos) {
		this.modulos = modulos;
	}

}
