package centroformacion.modelo;
// Generated 3 dic 2024, 19:02:01 by Hibernate Tools 5.4.33.Final

/**
 * LineaMatriculaId generated by hbm2java
 */
public class LineaMatriculaId implements java.io.Serializable {

	private int codigoMatricula;
	private int codigoModulo;

	public LineaMatriculaId() {
	}

	public LineaMatriculaId(int codigoMatricula, int codigoModulo) {
		this.codigoMatricula = codigoMatricula;
		this.codigoModulo = codigoModulo;
	}

	public int getCodigoMatricula() {
		return this.codigoMatricula;
	}

	public void setCodigoMatricula(int codigoMatricula) {
		this.codigoMatricula = codigoMatricula;
	}

	public int getCodigoModulo() {
		return this.codigoModulo;
	}

	public void setCodigoModulo(int codigoModulo) {
		this.codigoModulo = codigoModulo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LineaMatriculaId))
			return false;
		LineaMatriculaId castOther = (LineaMatriculaId) other;

		return (this.getCodigoMatricula() == castOther.getCodigoMatricula())
				&& (this.getCodigoModulo() == castOther.getCodigoModulo());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodigoMatricula();
		result = 37 * result + this.getCodigoModulo();
		return result;
	}

}
