package centroformacion.modelo;
// Generated 3 dic 2024, 19:02:01 by Hibernate Tools 5.4.33.Final

import java.math.BigDecimal;

/**
 * LineaMatricula generated by hbm2java
 */
public class LineaMatricula implements java.io.Serializable {

	private LineaMatriculaId id;
	private Matricula matricula;
	private Modulo modulo;
	private int repetidor;
	private BigDecimal calificacion1;
	private BigDecimal calificacion2;

	public LineaMatricula() {
	}

	public LineaMatricula(LineaMatriculaId id, Matricula matricula, Modulo modulo, int repetidor) {
		this.id = id;
		this.matricula = matricula;
		this.modulo = modulo;
		this.repetidor = repetidor;
	}

	public LineaMatricula(LineaMatriculaId id, Matricula matricula, Modulo modulo, int repetidor,
			BigDecimal calificacion1, BigDecimal calificacion2) {
		this.id = id;
		this.matricula = matricula;
		this.modulo = modulo;
		this.repetidor = repetidor;
		this.calificacion1 = calificacion1;
		this.calificacion2 = calificacion2;
	}

	public LineaMatriculaId getId() {
		return this.id;
	}

	public void setId(LineaMatriculaId id) {
		this.id = id;
	}

	public Matricula getMatricula() {
		return this.matricula;
	}

	public void setMatricula(Matricula matricula) {
		this.matricula = matricula;
	}

	public Modulo getModulo() {
		return this.modulo;
	}

	public void setModulo(Modulo modulo) {
		this.modulo = modulo;
	}

	public int getRepetidor() {
		return this.repetidor;
	}

	public void setRepetidor(int repetidor) {
		this.repetidor = repetidor;
	}

	public BigDecimal getCalificacion1() {
		return this.calificacion1;
	}

	public void setCalificacion1(BigDecimal calificacion1) {
		this.calificacion1 = calificacion1;
	}

	public BigDecimal getCalificacion2() {
		return this.calificacion2;
	}

	public void setCalificacion2(BigDecimal calificacion2) {
		this.calificacion2 = calificacion2;
	}

}
