package centroformacion.modelo;
// Generated 3 dic 2024, 19:02:01 by Hibernate Tools 5.4.33.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Matricula generated by hbm2java
 */
public class Matricula implements java.io.Serializable {

	private int codigo;
	private Alumno alumno;
	private int agnoAcademico;
	private String estado;
	private BigDecimal importe;
	private Set lineaMatriculas = new HashSet(0);

	public Matricula() {
	}

	public Matricula(int codigo, Alumno alumno, int agnoAcademico, String estado, BigDecimal importe) {
		this.codigo = codigo;
		this.alumno = alumno;
		this.agnoAcademico = agnoAcademico;
		this.estado = estado;
		this.importe = importe;
	}

	public Matricula(int codigo, Alumno alumno, int agnoAcademico, String estado, BigDecimal importe,
			Set lineaMatriculas) {
		this.codigo = codigo;
		this.alumno = alumno;
		this.agnoAcademico = agnoAcademico;
		this.estado = estado;
		this.importe = importe;
		this.lineaMatriculas = lineaMatriculas;
	}

	public int getCodigo() {
		return this.codigo;
	}

	public void setCodigo(int codigo) {
		this.codigo = codigo;
	}

	public Alumno getAlumno() {
		return this.alumno;
	}

	public void setAlumno(Alumno alumno) {
		this.alumno = alumno;
	}

	public int getAgnoAcademico() {
		return this.agnoAcademico;
	}

	public void setAgnoAcademico(int agnoAcademico) {
		this.agnoAcademico = agnoAcademico;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public BigDecimal getImporte() {
		return this.importe;
	}

	public void setImporte(BigDecimal importe) {
		this.importe = importe;
	}

	public Set getLineaMatriculas() {
		return this.lineaMatriculas;
	}

	public void setLineaMatriculas(Set lineaMatriculas) {
		this.lineaMatriculas = lineaMatriculas;
	}

	@Override
	public String toString() {
		return "Matricula [codigo=" + codigo + ", alumno=" + alumno + ", agnoAcademico=" + agnoAcademico + ", estado="
				+ estado + ", importe=" + importe + "]";
	}

}
