package libreria.modelo;
// Generated 14 nov 2024, 19:13:39 by Hibernate Tools 5.4.33.Final

/**
 * DisponibilidadId generated by hbm2java
 */
public class DisponibilidadId implements java.io.Serializable {

	private Libro libro;
	private Tienda tienda;

	public DisponibilidadId() {
	}

	public DisponibilidadId(Libro libro, Tienda tienda) {
		this.libro = libro;
		this.tienda = tienda;
	}

	public Libro getLibro() {
		return this.libro;
	}

	public void setLibro(Libro libro) {
		this.libro = libro;
	}

	public Tienda getTienda() {
		return this.tienda;
	}

	public void setTienda(Tienda tienda) {
		this.tienda = tienda;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DisponibilidadId))
			return false;
		DisponibilidadId castOther = (DisponibilidadId) other;

		return ((this.getLibro() == castOther.getLibro()) || (this.getLibro() != null && castOther.getLibro() != null
				&& this.getLibro().equals(castOther.getLibro())))
				&& ((this.getTienda() == castOther.getTienda()) || (this.getTienda() != null
						&& castOther.getTienda() != null && this.getTienda().equals(castOther.getTienda())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getLibro() == null ? 0 : this.getLibro().hashCode());
		result = 37 * result + (getTienda() == null ? 0 : this.getTienda().hashCode());
		return result;
	}

}
