package libreria.modelo;
// Generated 14 nov 2024, 19:13:39 by Hibernate Tools 5.4.33.Final

import java.util.Date;

/**
 * Disponibilidad generated by hbm2java
 */
public class Disponibilidad implements java.io.Serializable {

	private DisponibilidadId id;
	private int cantidad;
	private Date fechaUltimaReposicion;

	public Disponibilidad() {
	}

	public Disponibilidad(DisponibilidadId id, int cantidad, Date fechaUltimaReposicion) {
		this.id = id;
		this.cantidad = cantidad;
		this.fechaUltimaReposicion = fechaUltimaReposicion;
	}

	public DisponibilidadId getId() {
		return this.id;
	}

	public void setId(DisponibilidadId id) {
		this.id = id;
	}

	public int getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(int cantidad) {
		this.cantidad = cantidad;
	}

	public Date getFechaUltimaReposicion() {
		return this.fechaUltimaReposicion;
	}

	public void setFechaUltimaReposicion(Date fechaUltimaReposicion) {
		this.fechaUltimaReposicion = fechaUltimaReposicion;
	}

}
