package libreria.modelo;
// Generated 14 nov 2024, 19:13:39 by Hibernate Tools 5.4.33.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Escritor generated by hbm2java
 */
public class Escritor implements java.io.Serializable {

	private Integer codigo;
	private String nombre;
	private String nacionalidad;
	private Date fechaNacimiento;
	private Date fechaFallecimiento;
	private Set libros = new HashSet(0);

	public Escritor() {
	}

	public Escritor(String nombre, String nacionalidad, Date fechaNacimiento) {
		this.nombre = nombre;
		this.nacionalidad = nacionalidad;
		this.fechaNacimiento = fechaNacimiento;
	}

	public Escritor(String nombre, String nacionalidad, Date fechaNacimiento, Date fechaFallecimiento, Set libros) {
		this.nombre = nombre;
		this.nacionalidad = nacionalidad;
		this.fechaNacimiento = fechaNacimiento;
		this.fechaFallecimiento = fechaFallecimiento;
		this.libros = libros;
	}

	public Integer getCodigo() {
		return this.codigo;
	}

	public void setCodigo(Integer codigo) {
		this.codigo = codigo;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getNacionalidad() {
		return this.nacionalidad;
	}

	public void setNacionalidad(String nacionalidad) {
		this.nacionalidad = nacionalidad;
	}

	public Date getFechaNacimiento() {
		return this.fechaNacimiento;
	}

	public void setFechaNacimiento(Date fechaNacimiento) {
		this.fechaNacimiento = fechaNacimiento;
	}

	public Date getFechaFallecimiento() {
		return this.fechaFallecimiento;
	}

	public void setFechaFallecimiento(Date fechaFallecimiento) {
		this.fechaFallecimiento = fechaFallecimiento;
	}

	public Set getLibros() {
		return this.libros;
	}

	public void setLibros(Set libros) {
		this.libros = libros;
	}

}
