package libreria.modelo;
// Generated 14 nov 2024, 19:13:39 by Hibernate Tools 5.4.33.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Libro generated by hbm2java
 */
public class Libro implements java.io.Serializable {

	private Integer codigo;
	private Escritor escritor;
	private String titulo;
	private int agnoPublicacion;
	private int numeroPaginas;
	private BigDecimal precio;
	private Set disponibilidads = new HashSet(0);

	public Libro() {
	}

	public Libro(Escritor escritor, String titulo, int agnoPublicacion, int numeroPaginas, BigDecimal precio) {
		this.escritor = escritor;
		this.titulo = titulo;
		this.agnoPublicacion = agnoPublicacion;
		this.numeroPaginas = numeroPaginas;
		this.precio = precio;
	}

	public Libro(Escritor escritor, String titulo, int agnoPublicacion, int numeroPaginas, BigDecimal precio,
			Set disponibilidads) {
		this.escritor = escritor;
		this.titulo = titulo;
		this.agnoPublicacion = agnoPublicacion;
		this.numeroPaginas = numeroPaginas;
		this.precio = precio;
		this.disponibilidads = disponibilidads;
	}

	public Integer getCodigo() {
		return this.codigo;
	}

	public void setCodigo(Integer codigo) {
		this.codigo = codigo;
	}

	public Escritor getEscritor() {
		return this.escritor;
	}

	public void setEscritor(Escritor escritor) {
		this.escritor = escritor;
	}

	public String getTitulo() {
		return this.titulo;
	}

	public void setTitulo(String titulo) {
		this.titulo = titulo;
	}

	public int getAgnoPublicacion() {
		return this.agnoPublicacion;
	}

	public void setAgnoPublicacion(int agnoPublicacion) {
		this.agnoPublicacion = agnoPublicacion;
	}

	public int getNumeroPaginas() {
		return this.numeroPaginas;
	}

	public void setNumeroPaginas(int numeroPaginas) {
		this.numeroPaginas = numeroPaginas;
	}

	public BigDecimal getPrecio() {
		return this.precio;
	}

	public void setPrecio(BigDecimal precio) {
		this.precio = precio;
	}

	public Set getDisponibilidads() {
		return this.disponibilidads;
	}

	public void setDisponibilidads(Set disponibilidads) {
		this.disponibilidads = disponibilidads;
	}

	@Override
	public String toString() {
		return "Libro [codigo=" + codigo +
				", escritor=" + escritor.getCodigo() + ", titulo=" + titulo + ", agnoPublicacion="
				+ agnoPublicacion + ", numeroPaginas=" + numeroPaginas + ", precio=" + precio + "]";
	}
	
	

}
